#!/usr/bin/env bash
__igloo_bash::lib::util::sync::util::array::get_module_realpath() {
  if hash realpath 2>/dev/null; then
    printf "$(realpath "${BASH_SOURCE[0]}")"
  else
    printf "$(readlink "${BASH_SOURCE[0]}")"
  fi
}

__igloo_bash::lib::util::sync::util::array::get_self_name() {
  printf "$(basename $(__igloo_bash::lib::util::sync::util::array::get_module_realpath))"
}

# Checks if a array contains the specified element.
#
# Note that the elements of the array must be passed as variable expansion with quotes to avoid whiespace breakage!
#
# @param $1 the element to search for
# @param $2 the array to search
# @return 0 if the array contains the element, 1 or higher otherwise
# @example __igloo_bash::lib::util::sync::util::array::contains_element "yogurt" "${array[@]}"
__igloo_bash::lib::util::sync::util::array::contains_element() {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}
